// flags on digital pool, search for
// Taiwan: static/media/tw-ioc
// Japan:  jp.svg

const twMapping = {
  "CHANG Chih Hsuan": "張芷瑄",
  "CHANG Hsin Yu": "章心宥",
  "CHANG Jung Lin": "張榮麟",
  "Chang Lichia": "張莉佳",
  "CHANG Ming Hsiung": "張明雄",
  "CHANG Pei Wei": "張裴瑋",
  "CHANG Tzu Chien": "張子謙",
  "CHANG YI": "張翼",
  "CHANG Yu Lung": "張玉龍",
  "CHANG Yu Yuan": "章又元",
  "CHAO Fong Pang": "趙豐邦",
  "Chao Shih Fan": "趙世璠",
  "Chen Chen Wei": "陳臻為",
  "CHEN Chia Hua": "陳佳樺",
  "CHEN Hsin Ting": "陳信廷",
  "CHEN Pin Lin": "陳品霖",
  "CHEN Ying Chieh": "陳英傑",
  "CHENG Shun Yang": "鄭舜陽",
  "CHIANG Shui Ching": "江水淨",
  "CHIEN Bo Chun": "簡伯鈞",
  "Chien Ching Ju": "簡敬儒",
  "CHIU Chun Yuan": "邱俊元",
  "CHIU Po Han": "邱柏翰",
  "CHIU Wei Yu": "施威宇",
  "CHOU Chia Chia": "周家嘉",
  "CHOU Chia Lin": "周家麟",
  "CHOU Chieh Yu": "周婕妤",
  "CHU Hung Ming": "朱宏銘",
  "CHUANG Yaw Lin": "莊曜霖",
  "FANG Hsiao Lang": "方小郎",
  "FU Che Wei": "傅哲偉",
  "Hong xin Yu": "洪欣妤",
  "HSIEH Chia Chen": "謝佳臻",
  "Hsieh Chia Hsiang": "謝佳祥",
  "HSIEH Shang Yu": "謝尚諭",
  "HSU Jui An": "許睿安",
  "HSU Shih Wei": "許世瑋",
  "HSUEH Wen Chang": "薛文章",
  "Huang Bo Song": "黃勃崧",
  "HUANG Wei Lun": "黃唯綸",
  "JIANG Xin Xing": "江信興",
  "KAO shun yang": "高舜暘",
  "Kazuo FURUTA": "古田和男",
  "KO Pin Yi": "柯秉逸",
  "KO Ping Chung": "柯秉中",
  "KO Ping Han": "柯秉漢",
  "KUO Chun Nan": "郭俊男",
  "KUO Hsuan Wei": "郭玄偉",
  "KUO Po Cheng": "郭柏成",
  "LAI Ming Huan": "賴明煥",
  "LAI Wei Qi": "賴瑋棋",
  "LEE Kun Fang": "李昆芳",
  "LEE Wei Jen": "李維仁",
  "Li Zih Min": "李自民",
  "LIAO Hung Yen": "廖泓雁",
  "LIAO Ying Kai": "廖英凱",
  "LIEN Chih Wei": "連治瑋",
  "LIN Chao Tse": "林肇則",
  "LIN Cheng Yen": "林承諺",
  "LIN Huang Kuei": "林煌貴",
  "LIN Jia Zheng": "林家正",
  "LIN Mei Wen": "林媺玟",
  "LIN Shih Kai": "林詩凱",
  "LIN Ta Li": "林達理",
  "LIN Tsung Han": "林宗翰",
  "LIU Cheng Hsiung": "劉正雄",
  "LIU Chien Hung": "劉建弘",
  "LIU Chun Chuan": "劉峻銓",
  "LIU Ri Teng": "劉日騰",
  "LIU SHAO CHIANG": "劉少強",
  "LIU Shin Mei": "柳信美",
  "LIU Yun Cheng": "劉運程",
  "LU Hui Chan": "呂輝展",
  "SHAO Yu Hsin": "邵育鑫",
  "SUN Yi Hsuan": "孫翌軒",
  "TAI Chi Hsiang": "戴啟祥",
  "TANG Ching Ting": "唐境霆",
  "Tsai Cheng Ta": "蔡承達",
  "TSAI Pei Chun": "蔡佩君",
  "Tu Wei Chieh": "杜偉傑",
  "WANG Chi Sheng": "王志聖",
  "WANG Chih Yung": "王智勇",
  "WANG Ching Feng": "王清鋒",
  "WANG Chuan Min": "王權敏",
  "WANG Hung Hsiang": "王泓翔",
  "WU Cheng Lin": "吳政霖",
  "WU Jia Qing": "吳珈慶",
  "WU Kun Lin": "吳坤霖",
  "YANG Dong Yu": "楊東裕",
  "YANG Gong Hao": "楊恭豪",
  "YE Chun Hung": "葉峻宏",
  "YU Li Si": "余豊熙",
  "ZENG Huan Zhong": "曾煥中",
  "Zheng Sen": "鄭森",
  "ZHUANG Zhi Yu": "莊智宇",
};

const sgMapping = {
  "Toh Lian Han": "卓連漢",
};

// source: https://jpba.ne.jp/
const jpMapping = {
  "Agata Yasuhiro": "安形泰宏",
  "Hayato Hijikata": "土方隼斗",
  "Hideki Yamakawa": "山川英樹",
  "Hiroshi Takenaka": "竹中寛",
  "Kenichi Uchigaki": "内垣建一",
  "Kouki Sugiyama": "杉山功起",
  "Masato Asano": "浅野正人",
  "Masato Yoshioka": "吉岡正登",
  "Naoyuki Oi": "大井直幸",
  "Norio Ogawa": "小川徳郎",
  "Ryosuke Maruoka": "丸岡良輔",
  "Ryota Tashiro": "田代亮太",
  "Shinnosuke Matukawa": "松川慎之介",
  "Takahashi Kunihiko": "高橋邦彦",
  "Takashi Uraoka": "浦岡隆志",
  "Yukio Akagariyama": "赤狩山幸男",
};

const cnMapping = {
  "Liu Nuoen": "刘诺恩",
  "Mei Yifei": "梅逸飞",
  "Ruan Yihui": "阮以辉",
  "Wang Can": "王灿",
  "Zhu Xihe": "朱熙禾",
};


const stringMapping = {
  ...twMapping,
  ...sgMapping,
  ...jpMapping,
  ...cnMapping,
};
